# Build default branch and PRs, publish only from default, uses hacks until this is fixed.
#   https://github.com/actions/starter-workflows/issues/2100
# Needs `STORE_LOGIN` configured:
#   https://github.com/snapcore/action-publish/blob/1ff0862b7fed38d4e843a2fdae55776ffd729986/README.md
# Change channel from default `edge` if needed.

name: Build and pubish snap package

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: build
      uses: snapcore/action-build@v1
    - id: publish
      if: github.ref == format('refs/heads/{0}', fromJSON('$default-branch'))
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        SNAPCRAFT_STORE_AUTH: candid
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
